use_frameworks!

platform :ios, '10.0'

target 'TestExtensionUI_Example' do
  pod 'TestExtensionUI', :path => '../'
  pod 'Kingfisher', '~> 5.2'

  target 'TestExtensionUI_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end
